### ISSUE TITLE
Edit news

### ISSUE THREAD

**Issue by kiznick** [p0ndja/WebDev#8]
Fatal error: Uncaught TypeError: mysqli_fetch_array() expects parameter 1 to be mysqli_result, bool given in ***/global/function.php:17 Stack trace: #0 ***/global/function.php(17): mysqli_fetch_array() #1 ***/global/function.php(47): getAnySQL() #2 ***/news/post.php(16): getPostdata() #3 {main} thrown in ***/global/function.php on line 17

**Comment by p0ndja** [comment]
Wrong database format -- Use the latest one
[**https://github.com/p0ndja/WebDev/blob/master/template.sql**](https://github.com/p0ndja/WebDev/blob/master/template.sql)
